### ISSUE TITLE
scripts n-n.py and train_transe_CommonGen.py are not included

### ISSUE THREAD

**Issue by mukhal** [yeliu918/KG-BART#2]
Hello,

Thank you for your code. 

I tried running 
```
cd OpenKE
git clone -b OpenKE-PyTorch https://github.com/thunlp/OpenKE
cd benchmarks/CommonGen
python n-n.py
python train_transe_CommonGen.py
```
I can not find the scripts `n-n.py` or `train_transe_CommonGen.py`

Could you guide me here?

**Comment by yeliu918** [comment]
Hi, Mohammad

Thanks for pointing out this. It has been uploaded.

**Comment by mohammadKhalifa** [comment]
Hello,

Thanks but you have only uploaded `n-n.py`. `train_transe_CommonGen.py` is still missing.
