### ISSUE TITLE
Error running Test

### ISSUE THREAD

**Issue by jh-skaion** [yeliu918/KG-BART#8]
Hello,
i am interested on testing KG-BART but i am getting the following error:
![image](https://user-images.githubusercontent.com/82824999/133852411-99c11dde-a173-42a3-978e-384964b4dd0d.png)

can you advice?

**Comment by wangjs9** [comment]
...... do you really code?

**Comment by jh-skaion** [comment]
> ...... do you really code?

hello,
thank you for your replay. i was able to running it end to end with some modifications. i forgot i opened this issue, i will close it now.
thanks again for the reply
