### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by CheckEO** [yeliu918/KG-BART#9]
Please point out where the files of "conceptnet-assertions-5.7.0.csv" and "../OpenKE/benchmarks/CommonGen" are? When I ran reorder_src, the program asks these files.
Thanks.

**Comment by 1754699523** [comment]
> Please point out where the files of "conceptnet-assertions-5.7.0.csv" and "../OpenKE/benchmarks/CommonGen" are? When I ran reorder_src, the program asks these files. Thanks.

hi,I meet same question ,could you help me?thank you
